
export const EUMEDICAL_CROSS_VIEWBOX = "0 0 100 100";

const ARM_LENGTH = 92;
const ARM_THICKNESS = 28;
const ARM_OFFSET = (100 - ARM_LENGTH) / 2;
const THICKNESS_OFFSET = (100 - ARM_THICKNESS) / 2;

export const EUMEDICAL_CROSS_BARS = [
  { x: ARM_OFFSET, y: THICKNESS_OFFSET, width: ARM_LENGTH, height: ARM_THICKNESS, rx: ARM_THICKNESS / 2 }, 
  { x: THICKNESS_OFFSET, y: ARM_OFFSET, width: ARM_THICKNESS, height: ARM_LENGTH, rx: ARM_THICKNESS / 2 }, 
] as const;

export const EUMEDICAL_ORANGE = "#e79f1a";
